/**
 * Builds the uploadable skill package, and guards the files it derives.
 *
 *   node scripts/build-skill.mjs          write contenthero/agents/openai.yaml
 *   node scripts/build-skill.mjs --check  fail if anything derived has drifted (CI)
 *   node scripts/build-skill.mjs --zip    write, then package dist/contenthero.zip
 *
 * WHY A ZIP AT ALL. Chat apps install a skill by UPLOAD, not by clone: claude.ai and ChatGPT take a
 * `.zip` whose root is the skill folder, and Gemini takes that same folder unzipped. Measured
 * 2026-09-24 by real uploads on all three, including a canary proving Gemini keeps `references/`.
 * The zip is DERIVED from this repo on every release, never hand-built, so it cannot drift from the
 * skill it packages.
 *
 * WHY openai.yaml IS GENERATED. ChatGPT reads `agents/openai.yaml` for the skill's display name,
 * icon, brand color, and the MCP server it depends on. With none, ChatGPT invents a placeholder
 * (a lightning bolt). Every value already lives in `.codex-plugin/plugin.json` and `.mcp.json`, so
 * writing it by hand would be a second copy of each. It is generated from those, committed so a
 * cloned install has it too, and `--check` fails CI the moment the committed file disagrees.
 *
 * WHY THE VERSION CHECK. The version is spelled in six places. A release whose manifests disagree
 * ships a package that describes itself two ways.
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'

const root = new URL('..', import.meta.url).pathname
const read = (p) => readFileSync(join(root, p), 'utf8')
const json = (p) => JSON.parse(read(p))
const mode = process.argv[2] ?? '--write'
const failures = []

// ─── openai.yaml, derived ────────────────────────────────────────────────────
const iface = json('.codex-plugin/plugin.json').interface
const server = json('.mcp.json').mcpServers.contenthero
const q = (s) => JSON.stringify(s) // a JSON string is a valid YAML double-quoted scalar

const yaml = `# GENERATED by scripts/build-skill.mjs from .codex-plugin/plugin.json and .mcp.json. Do not edit.
interface:
  display_name: ${q(iface.displayName)}
  short_description: ${q(iface.shortDescription)}
  icon_small: "./assets/icon.svg"
  icon_large: "./assets/icon.svg"
  brand_color: ${q(iface.brandColor)}
  default_prompt: ${q(iface.defaultPrompt[0])}

dependencies:
  tools:
    - type: "mcp"
      value: "contenthero"
      description: "ContentHero hosted MCP server (OAuth, runs against your account and credits)"
      transport: "streamable_http"
      url: ${q(server.url)}
`

const yamlPath = 'contenthero/agents/openai.yaml'
if (!existsSync(join(root, 'contenthero/assets/icon.svg'))) failures.push('contenthero/assets/icon.svg is missing')

if (mode === '--check') {
  const committed = existsSync(join(root, yamlPath)) ? read(yamlPath) : ''
  if (committed !== yaml) failures.push(`${yamlPath} is stale: run \`npm run build:skill\` and commit the result`)
} else {
  mkdirSync(join(root, 'contenthero/agents'), { recursive: true })
  writeFileSync(join(root, yamlPath), yaml)
}

// ─── the description is ONE physical line ────────────────────────────────────
// YAML folds a wrapped `>-` description into one line, and claude.ai does. ChatGPT does NOT: it
// rendered every wrap as a hard line break (measured 2026-09-24, v0.2.1 test upload). A block
// scalar holding a single line is the form proven on claude.ai, ChatGPT and Gemini.
{
  const lines = read('contenthero/SKILL.md').split('\n')
  const at = lines.findIndex((l) => l.startsWith('description:'))
  const inline = lines[at].replace(/^description:\s*/, '')
  const valueLines = /^[>|]/.test(inline)
    ? lines.slice(at + 1).findIndex((l) => !/^\s+\S/.test(l))
    : 1
  if (at < 0) failures.push('SKILL.md has no description')
  else if (valueLines !== 1) failures.push(`SKILL.md description spans ${valueLines} lines; ChatGPT shows each wrap as a line break. Keep it on one line.`)
}

// ─── one version, six spellings ──────────────────────────────────────────────
const version = read('VERSION').trim()
const spellings = {
  'package.json': json('package.json').version,
  '.claude-plugin/plugin.json': json('.claude-plugin/plugin.json').version,
  '.claude-plugin/marketplace.json': json('.claude-plugin/marketplace.json').plugins[0].version,
  '.codex-plugin/plugin.json': json('.codex-plugin/plugin.json').version,
  '.cursor-plugin/plugin.json': json('.cursor-plugin/plugin.json').version,
}
for (const [file, v] of Object.entries(spellings)) {
  if (v !== version) failures.push(`${file} says ${v}, VERSION says ${version}`)
}

if (failures.length) {
  console.error(`build-skill: ${failures.length} problem(s)\n  - ${failures.join('\n  - ')}`)
  process.exit(1)
}

// ─── the package ─────────────────────────────────────────────────────────────
if (mode === '--zip') {
  const out = join(root, 'dist/contenthero.zip')
  rmSync(join(root, 'dist'), { recursive: true, force: true })
  mkdirSync(join(root, 'dist'))
  // The folder, not its contents, is the zip root: every host requires SKILL.md under it.
  execFileSync('zip', ['-r', '-X', '-q', out, 'contenthero', '-x', '*.DS_Store'], { cwd: root, stdio: 'inherit' })
  console.log(`build-skill: wrote dist/contenthero.zip (v${version})`)
} else {
  console.log(`build-skill: ${mode === '--check' ? 'derived files are current' : `wrote ${yamlPath}`} (v${version})`)
}
